modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/tomas65107/moretraffic/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://tomas65107.dev/moretraffic"
logoFile="moretraffic.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="trafficcraft"
mandatory=true
versionRange="${trafficcraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dragonlib"
mandatory=true
versionRange="${dragonlib_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

